# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Biography of Jian Jian (建健)
email: jjian03@syr.edu
description: >- # this means to ignore newlines until "baseurl:"
  This website is Jian Jian' portfolio.
  Jian Jian previously was a Senior Java Software Engineer.
  He is also a Data Science professional.
github_username: UKGANG
minimal_mistakes_skin: default
search: true
header:
  teaser: "/assets/images/bio-photo.jpg"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-92344ML5YY"
    anonymize_ip: false # defaultZ

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Jian Jian (Ken)"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Senior ML Engineer at Deepcell<br>Data Scientist<br>Senior Java Software Engineer<br>Research & Teaching Assistant"
  links:
    - label: "Silicon Valley, CA, United State"
      icon: "fas fa-fw fa-map-marker-alt"
      url: "https://www.google.com/maps/place/Silicon+Valley,+CA/@37.402473,-122.3212843,10z/data=!3m1!4b1!4m5!3m4!1s0x808fb68ad0cfc739:0x7eb356b66bd4b50e!8m2!3d37.387474!4d-122.0575434"
    - label: "jjian03@syr.edu"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:jjian03@syr.edu"
    - label: "+1 (315) 802 9717"
      icon: "fas fa-fw fa-mobile"
      url: "tel:+13158029717"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://jianjian-portfolio.github.io/about/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/UKGANG"
    - label: "Lab"
      icon: "fas fa-fw fa-flask"
      url: "https://scienceofscience.org/people/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/jian-jian/"

footer:
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://jianjian-portfolio.github.io/about/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/UKGANG"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/jian-jian/"
    - label: "Lab"
      icon: "fas fa-fw fa-flask"
      url: "https://scienceofscience.org/people/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _leadership
  - scope:
      path: "_leadership"
      type: leadership
    values:
      layout: single
      author_profile: true
      share: true
  # _certificate
  - scope:
      path: "_certificate"
      type: certificate
    values:
      layout: single
      author_profile: true
      share: true
  # _project
  - scope:
      path: "_project"
      type: project
    values:
      layout: single
      author_profile: true
      share: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

collections:
  project:
    output: true
    permalink: /:collection/:path/
  leadership:
    output: true
    permalink: /:collection/:path/
