# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Biography of Jian Jian (建健)
email: jjian03@syr.edu
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
github_username: UKGANG
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Jian Jian"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Data Scientist at IPwe<br>Senior Java Software Engineer<br>Research & Teaching Assistant"
  links:
    - label: "Syracuse, NY, USA"
      icon: "fas fa-fw fa-map-marker-alt"
      url: ""
    - label: "jjian03@syr.edu"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:jjian03@syr.edu"
    - label: "+1 (315) 802 9717"
      icon: "fas fa-fw fa-mobile"
      url: ""
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://jianjian-portfolio.github.io/about/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/UKGANG"
    - label: "Lab"
      icon: "fas fa-fw fa-flask"
      url: "https://scienceofscience.org/people/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/ken-j/"

footer:
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://jianjian-portfolio.github.io/about/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/UKGANG"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ken-j/"
    - label: "Lab"
      icon: "fas fa-fw fa-flask"
      url: "https://scienceofscience.org/people/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _project
  - scope:
      path: "_project"
      type: project
    values:
      layout: single
      author_profile: false
      share: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

collections:
  project:
    output: true
    permalink: /:collection/:path/
    order:
      - sata-project.md
      - bvi-project.md